service: slack-thread-mover

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'prod'}
  timeout: 30
  memorySize: 256
  
  environment:
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_USER_TOKEN: ${env:SLACK_USER_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}

functions:
  slackBot:
    handler: lambda.handler
    events:
      - http:
          path: /slack/events
          method: post
      - http:
          path: /slack/commands
          method: post

plugins:
  - serverless-offline 